{
 "title": "Apache",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apache_cpuload" }
   ]
  },
  {
   "title": "Requests per secod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_accesses_total[2m])"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apache_workers", "legendFormat": "{{state}}" }
   ]
  }
 ]
}