{
 "title": "Envoy SLIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "HTTP codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\",}[5m])",
     "legendFormat": "{{envoy_response_code_class}}00"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[5m])) / sum(rate(envoy_http_downstream_rq_xx[5m]))",
     "legendFormat": "SR"
    }
   ]
  },
  {
   "title": "Requests per second Downstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_completed{envoy_http_conn_manager_prefix=\"ingress_http\"}[5m])",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Requests per second Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total[5m])",
     "legendFormat": "rqs"
    }
   ]
  },
  {
   "title": "Latency Percentiles Downstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"ingress_http\"}[5m]))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"ingress_http\"}[5m]))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"ingress_http\"}[5m]))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Latency Percentiles Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(envoy_cluster_upstream_rq_time_bucket[5m]))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, rate(envoy_cluster_upstream_rq_time_bucket[5m]))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket[5m]))",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}