apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: db
        - name: WORDPRESS_DB_NAME
          value: exampledb
        - name: WORDPRESS_DB_PASSWORD
          value: examplepass
        - name: WORDPRESS_DB_USER
          value: exampleuser
        image: wordpress
        name: wordpress
        ports:
        - containerPort: 80
          name: web
      - image: bonniernews/apache_exporter
        name: exporter
        ports:
        - containerPort: 9117
          name: metrics
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: web
  - port: 9117
    protocol: TCP
    targetPort: 9117
    name: metrics
  selector:
    io.kompose.service: wordpress
  type: LoadBalancer

# vim: ts=2 sts=2 sw=2 et
